sudo: required
cache: bundler
services:
  - docker
env:
  global:
    - COMPOSE_FILE: docker-compose.ci.yml
    - TINYTDS_VERSION=1.3.0
    - ACTIVERECORD_UNITTEST_HOST=localhost
    - ACTIVERECORD_UNITTEST_DATASERVER=localhost
    - JRUBY_OPTS="--dev -X+O -J-Xmx2048m"
rvm:
  - 2.2.5
  - 2.3.1
  - 2.4.0
  - jruby
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
install:
  - docker-compose build --build-arg TARGET_VERSION=$TARGET_VERSION
script:
  - docker-compose run ci
matrix:
  include:
    - name: 2.3.8
      env: TARGET_VERSION=2.3.8
    - name: 2.4.5
      env: TARGET_VERSION=2.4.5
    - name: 2.5.3
      env: TARGET_VERSION=2.5.3
    - name: 2.6.0
      env: TARGET_VERSION=2.6.0
