sudo: required
cache: bundler
services:
  - docker
env:
  global:
    - ACTIVERECORD_UNITTEST_HOST=localhost
    - ACTIVERECORD_UNITTEST_DATASERVER=localhost
    - ARJDBC_BRANCH=mssql-support
rvm:
  - jruby-9.1.17.0
  - jruby-9.2.7.0
before_install:
  - export PATH=/opt/local/bin:$PATH
  - docker info
  - sudo ./test/bin/setup.sh
#  - sudo ./test/bin/install-openssl.sh
#  - openssl version
#  - sudo ./test/bin/install-freetds.sh
#  - tsql -C
install:
  - export PATH=/opt/local/bin:$PATH
  - gem install bundler
  - bundle --version
  - bundle install
script:
  - bundle exec rake
branches:
  only:
  - /.*-stable-jdbc$/
matrix:
  allow_failures:
  - rmv: jruby-9.1.17.0
